criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.001
  weight_decay: 0.01

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "cifar10_resnet18_learn_trans" # spatial sampling
  n_epochs: 100
  batch_size: 32

quantize:
  weight_bit: 8

noise:
  phase_bias: 1
  phase_noise_std: 0
  gamma_noise_std: 0.002
  crosstalk_factor: 0.005
  random_state: 42

sl: # subspace learning
  noisy_identity: 1

sparse:
  bp_spatial_sparsity: 0
  bp_column_sparsity: 0
  bp_input_sparsify_first_conv: 0
  bp_input_norm: "none"

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/resnet18/trans"
  model_comment: ""
  resume: 1
  restore_checkpoint: "./checkpoint/cifar10/resnet18/trans_pm/SparseBP_MZI_ResNet18_wb-8_ib-32_icalg-zcd_icadapt-0_icbest-1_ic-400_acc-67.39_epoch-400.pt"
  restore_checkpoint_pretrained:  "" #"./checkpoint/fmnist/cnn/pretrain/SparseBP_MZI_CNN_wb-32_ib-32__acc-92.66_epoch-79.pt"

model:
  name: "SparseBP_MZI_ResNet18"
  mode: "usv"

debug:
  verbose: 1

