dataset:
  num_workers: 0

criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.001
  weight_decay: 0.01

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0.0005

run:
  experiment: "fmnist_cnn2_learn_search" # compare gradient
  n_epochs: 10
  batch_size: 32

quantize:
  weight_bit: 8

noise:
  phase_bias: 1
  gamma_noise_std: 0.002
  crosstalk_factor: 0.005
  random_state: 42

sl: # subspace learning
  noisy_identity: 0

sparse:
  bp_data_sparsity: 0
  bp_data_alg: smb # smd: sto. mini-batch drop; smb: standard mini-batch; is: importance sampling
  bp_forward_weight_sparsity: 0
  bp_feedback_weight_sparsity: 0
  bp_feedback_alg: "topk"
  bp_feedback_norm: "none"
  bp_input_sparsity: 0
  bp_spatial_sparsity: 0
  bp_column_sparsity: 0
  bp_input_norm: "none"
  bp_rank: 8
  bp_rank_alg: "topk"
  bp_rank_sign: 0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "fmnist/cnn2/search"
  model_comment: ""
  resume: 0
  restore_checkpoint: ./checkpoint/fmnist/cnn/map/SparseBP_MZI_CNN_wb-8_ib-32_icalg-zcd_icadapt-0_icbest-1__acc-90.10_epoch-540.pt
  restore_checkpoint_pretrained: "" #"./checkpoint/fmnist/cnn/pretrain/SparseBP_MZI_CNN_wb-32_ib-32__acc-92.66_epoch-79.pt"
model:
  name: "SparseBP_MZI_CNN"
  mode: "usv"

debug:
  verbose: 1

