criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.0

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

quantize:
  weight_bit: 32

noise:
  phase_bias: 0
  phase_noise_std: 0
  gamma_noise_std: 0
  crosstalk_factor: 0
  random_state: 42

ic: # identity calibration
  alg: zcd # [zgd, ztp, zcd]
  adaptive: 1
  best_record: 1

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "mnist/cnn2/map"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""

model:
  name: "SparseBP_MZI_CNN"
  mode: "usv"

debug:
  verbose: 1

