dataset:
  name: cifar10
  root: "./data"
  num_workers: 2
  img_height: 32
  img_width: 32
  in_channel: 3
  n_class: 10
  transform: augmented

criterion:
  name: ce

optimizer:
  name: sgd
  lr: 0.02
  momentum: 0.9
  weight_decay: 0.000001

scheduler:
  name: cosine
  lr_min: 0.00002

run:
  experiment: "cifar10_resnet18_pretrain"
  n_epochs: 200
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

quantize:
  weight_bit: 32
  input_bit: 32

noise:
  phase_noise_std: 0
  gamma_noise_std: 0
  crosstalk_factor: 0
  random_state: 42

sparse:
  bp_forward_weight_sparsity: 0
  bp_feedback_weight_sparsity: 0
  bp_input_sparsity: 0
  bp_spatial_sparsity: 0
  bp_column_sparsity: 0
  bp_rank: 8

regularization:
  lambda_1 : 0
  lambda_2 : 0
  lambda_3 : 0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/resnet/pretrain"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""

model:
  name: "SparseBP_MZI_ResNet18"
  mode: "weight"
  block_list: [8, 8, 8, 8, 8, 8]
  act: relu
  act_thres: 4
  norm: bn

debug:
  verbose: 1

