dataset:
  name: fashionmnist
  root: "./data"
  num_workers: 2
  img_height: 28
  img_width: 28
  in_channel: 1
  n_class: 10
  transform: basic

criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.1
  weight_decay: 0.01

scheduler:
  name: exp
  lr_gamma: 0.99
  lr_min: 0.0245

run:
  experiment: "fmnist_cnn_map"
  cali_n_epochs: 400
  map_n_epochs: 1
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

quantize:
  weight_bit: 8
  input_bit: 32

noise:
  phase_bias: 1
  phase_noise_std: 0
  gamma_noise_std: 0.002
  crosstalk_factor: 0.005
  random_state: 42

ic: # identity calibration
  alg: zcd # [zgd, ztp, zcd]
  adaptive: 1
  best_record: 1

pm: # parallel mapping
  alg: zcd # [zgd, ztp, zcd]
  adaptive: 1
  best_record: 1
  ideal_I: 1

sparse:
  bp_forward_weight_sparsity: 0
  bp_feedback_weight_sparsity: 0
  bp_input_sparsity: 0
  bp_spatial_sparsity: 0
  bp_column_sparsity: 0
  bp_rank: 8

regularization:
  lambda_1 : 0
  lambda_2 : 0
  lambda_3 : 0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "fmnist/cnn/map"
  model_comment: ""
  resume: 1
  restore_checkpoint: "./checkpoint/fmnist/cnn/pretrain/SparseBP_MZI_CNN_wb-32_ib-32__acc-92.66_epoch-79.pt"

model:
  name: "SparseBP_MZI_CNN"
  mode: "weight"
  kernel_list: [16, 16]
  kernel_size_list: [3, 3]
  hidden_list: [64]
  block_list: [8, 8, 8]
  stride_list: [1, 1]
  padding_list: [1, 1]
  pool_out_size: 5
  act: relu
  act_thres: 4
  norm: bn

debug:
  verbose: 1

