dataset:
  name: cifar10
  root: "./data"
  num_workers: 2
  img_height: 32
  img_width: 32
  in_channel: 3
  n_class: 10
  transform: augmented

criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.001
  weight_decay: 0.01

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0.00002

run:
  experiment: "cifar10_vgg8_learn"
  n_epochs: 1
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

quantize:
  weight_bit: 8
  input_bit: 32

noise:
  phase_noise_std: 0
  gamma_noise_std: 0.002
  crosstalk_factor: 0.005
  random_state: 42

sparse:
  data_sparsity: 0.8 #0.9
  bp_forward_weight_sparsity: 0
  bp_feedback_weight_sparsity: 0.8 #0.8
  bp_feedback_alg: "topk"
  bp_feedback_norm: 0
  bp_input_sparsity: 0.5 #0.5
  bp_spatial_sparsity: 0.5 #0.5
  bp_column_sparsity: 0.8 #0.8
  bp_input_norm: 1 #1
  bp_rank: 7 #7
  bp_rank_alg: "uniform"
  bp_rank_sign: 0

regularization:
  lambda_1 : 0
  lambda_2 : 0
  lambda_3 : 0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/vgg/learn"
  model_comment: ""
  resume: 1
  # restore_checkpoint: "./checkpoint/cifar10/vgg/map/SparseBP_MZI_VGG8_wb-8_ib-32_bprank-8_bpfw-0_bpbw-0_bpin-0__acc-82.61_epoch-0.pt"
  restore_checkpoint: "./checkpoint/cifar10/vgg/map/SparseBP_MZI_VGG8_wb-8_ib-32_bprank-8_bpfw-0_bpbw-0_bpin-0__acc-87.25_epoch-0.pt"

model:
  name: "SparseBP_MZI_VGG8"
  mode: "usv"
  kernel_list: [16, 16]
  kernel_size_list: [3, 3]
  hidden_list: [64]
  block_list: [8, 8, 8]
  stride_list: [1, 1]
  padding_list: [1, 1]
  pool_out_size: 5
  act: relu
  act_thres: 4
  norm: bn

debug:
  verboise: 1

