criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.01

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 100
  batch_size: 32

quantize:
  weight_bit: 32
  input_bit: 32

noise:
  phase_bias: 0
  phase_noise_std: 0
  gamma_noise_std: 0
  crosstalk_factor: 0
  random_state: 42

ic: # identity calibration
  alg: zcd # [zgd, ztp, zcd]
  adaptive: 1
  best_record: 1

sparse:
  bp_forward_weight_sparsity: 0
  bp_feedback_weight_sparsity: 0
  bp_feedback_alg: "topk"
  bp_feedback_norm: "none"
  bp_input_sparsity: 0
  bp_spatial_sparsity: 0
  bp_column_sparsity: 0
  bp_input_norm: "none"
  bp_rank: 9
  bp_rank_alg: "topk"
  bp_rank_sign: 0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "svhn/vgg8/ss"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""

model:
  name: "SparseBP_MZI_VGG8"
  mode: "usv"

debug:
  verbose: 1

